### ISSUE TITLE
Date isn't shown in timezone format

### ISSUE THREAD

**Issue by lootsy** [leonidlezner/circlefinder#25]
There's a little to do with localization:

Despite my timezone is "Berlin" the date is shown in 10/1/18 instead of 1.10.2018.

**Comment by leonidlezner** [comment]
The date format does not depend on the time zone, but on the locale. Unfortunately the current locale is 'en', this is why the date is formatted US style.

I'll change the locale to de_DE (the UI will be still in English, because not translated yet).

Later the circlefinder will support multiple languages and thereby date formats.

**Comment by lootsy** [comment]
Of course you're right, that depends on the locale. That wasn't precise enough.

But in most cases it would be a good guess if one chooses timezone Berlin, the locale is set to "de_DE".
Of course it could be a japanese user moved to Berlin. Therefore these settings should not depend on each other.

**Comment by leonidlezner** [comment]
Timezone is just a temporary solution. The good solution would be to store user's location and derive the timezone and locale from it.

Also I only get a location from Facebook Login API, so I can't use the API until the "problem" with location is solved.

**Comment by lootsy** [comment]
Where do we want to discuss the "problem"?
Maybe here in an issue.

I think derivation of locale by location is a bad idea. Think of the japanese guys in 
![image](https://user-images.githubusercontent.com/21980459/42471878-a4964188-83bf-11e8-99c0-8e6efff28cc0.png). ;-)

**Comment by leonidlezner** [comment]
A new issue would be better as reopening this one :)
